#ifndef _lcd_gui_h_
#define _lcd_gui_h_

#include "lcd_roboto.h"

#define X_ADDRESS_END_SPO2_VALUE     69U
#define X_ADDRESS_START_SPO2_VALUE   15U
#define Y_ADDRESS_START_SPO2_VALUE   35U
#define X_ADDRESS_START_SPO2_TEXT    15U
#define Y_ADDRESS_START_SPO2_TEXT    15U
#define PIXELS_BETWEEN_SYMBOLS_SPO2   5U

#define X_ADDRESS_END_HR_VALUE      102U
#define X_ADDRESS_START_HR_VALUE     54U
#define Y_ADDRESS_START_HR_VALUE     86U
#define X_ADDRESS_START_HR_PICTURE   15U
#define Y_ADDRESS_START_HR_PICTURE   86U
#define PIXELS_BETWEEN_SYMBOLS_HR     3U

#define X_ADDRESS_START_FINGER_SENSOR     120U
#define Y_ADDRESS_START_FINGER_SENSOR      87U

#define X_ADDRESS_START_SHIT_DATA       120U
#define Y_ADDRESS_START_SHIT_DATA        87U

#define X_ADDRESS_START_BREATH_SENSORS_PICTURE    119U
#define Y_ADDRESS_START_BREATH_SENSORS_PICTURE     48U
#define X_ADDRESS_START_BREATH_SENSORS_CUBES 	  125U
#define Y_ADDRESS_START_BREATH_SENSOR0_CUBES       56U
#define Y_ADDRESS_START_BREATH_SENSOR1_CUBES 	   65U
#define X_SIZE_BREATH_SENSORS_CUBES                14U
#define Y_SIZE_BREATH_SENSORS_CUBES                 5U

#define X_ADDRESS_START_EMPTY_BATTERY     119U
#define Y_ADDRESS_START_EMPTY_BATTERY      15U
#define X_ADDRESS_START_FILLAREA_BATTERY  125U
#define Y_ADDRESS_START_FILLAREA_BATTERY   18U
#define X_SIZE_FILLAREA_BATTERY            17U
#define Y_SIZE_FILLAREA_BATTERY            10U

#define X_ADDRESS_START_BREATH_CUBES       88U
#define Y_ADDRESS_START_BREATH_CUBES       15U
#define PIXELS_BETWEEN_BREATH_CUBES         1U

#define X_ADDRESS_START_BATTERY_REFRESH   125U
#define Y_ADDRESS_START_BATTERY_REFRESH    18U
#define Y_ADDRESS_END_BATTERY_REFRESH      27U
#define PIXELS_BETWEEN_BATTERY_REFRESH      1U

#define X_ADDRESS_START_BLACK_WINDOW        8U
#define Y_ADDRESS_START_BLACK_WINDOW       14U
#define X_ADDRESS_END_BLACK_WINDOW        149U
#define Y_ADDRESS_END_BLACK_WINDOW        120U

#define X_ADDRESS_START_FINISH_SURVEY_PICTURE     56U
#define Y_ADDRESS_START_FINISH_SURVEY_PICTURE     14U
#define X_ADDRESS_START_FINISH_SURVEY_TEXT0       26U
#define Y_ADDRESS_START_FINISH_SURVEY_TEXT0       82U
#define X_ADDRESS_START_FINISH_SURVEY_TEXT1       39U
#define Y_ADDRESS_START_FINISH_SURVEY_TEXT1      104U

#define X_ADDRESS_LOGO_PICTURE                 50U
#define Y_ADDRESS_LOGO_PICTURE                 32U

#define X_ADDRESS_START_FORMATTING_PICTURE     60U
#define Y_ADDRESS_START_FORMATTING_PICTURE      9U
#define X_ADDRESS_START_FORMATTING_TEXT0        8U
#define Y_ADDRESS_START_FORMATTING_TEXT0       63U
#define X_ADDRESS_START_FORMATTING_TEXT1       15U
#define Y_ADDRESS_START_FORMATTING_TEXT1       81U
#define X_ADDRESS_START_FORMATTING_TEXT2       30U
#define Y_ADDRESS_START_FORMATTING_TEXT2       99U

#define X_ADDRESS_START_INSERT_SENSOR_PICTURE     30U
#define Y_ADDRESS_START_INSERT_SENSOR_PICTURE     23U
#define X_ADDRESS_START_INSERT_SENSOR_TEXT0       33U
#define Y_ADDRESS_START_INSERT_SENSOR_TEXT0       82U
#define X_ADDRESS_START_INSERT_SENSOR_TEXT1       53U
#define Y_ADDRESS_START_INSERT_SENSOR_TEXT1      104U

#define X_ADDRESS_START_INSERT_SDCARD_PICTURE     40U
#define Y_ADDRESS_START_INSERT_SDCARD_PICTURE     15U
#define X_ADDRESS_START_INSERT_SDCARD_TEXT0       44U
#define Y_ADDRESS_START_INSERT_SDCARD_TEXT0       82U
#define X_ADDRESS_START_INSERT_SDCARD_TEXT1       29U
#define Y_ADDRESS_START_INSERT_SDCARD_TEXT1      104U

#define X_ADDRESS_START_LOW_BATTERY_PICTURE       67U
#define Y_ADDRESS_START_LOW_BATTERY_PICTURE       23U
#define X_ADDRESS_START_LOW_BATTERY_TEXT0         42U
#define Y_ADDRESS_START_LOW_BATTERY_TEXT0         82U
#define X_ADDRESS_START_LOW_BATTERY_TEXT1          7U
#define Y_ADDRESS_START_LOW_BATTERY_TEXT1        104U

#define X_ADDRESS_START_USB_PICTURE       50U
#define Y_ADDRESS_START_USB_PICTURE       27U
#define X_ADDRESS_START_USB_TEXT0         29U
#define Y_ADDRESS_START_USB_TEXT0         82U
#define X_ADDRESS_START_USB_TEXT1         18U
#define Y_ADDRESS_START_USB_TEXT1        101U

#define X_ADDRESS_START_ERRORS_VALUE     40U
#define Y_ADDRESS_START_ERRORS_VALUE     15U
#define X_ADDRESS_START_ERRORS_TEXT0     34U
#define Y_ADDRESS_START_ERRORS_TEXT0     63U
#define X_ADDRESS_START_ERRORS_TEXT1     24U
#define Y_ADDRESS_START_ERRORS_TEXT1     86U
#define X_ADDRESS_START_ERRORS_TEXT2     17U
#define Y_ADDRESS_START_ERRORS_TEXT2    104U
#define PIXELS_BETWEEN_SYMBOLS_ERRORS     5U

#define X_ADDRESS_START_MAIN_UNIT_UPDATING_PICTURE     53U
#define Y_ADDRESS_START_MAIN_UNIT_UPDATING_PICTURE     23U
#define X_ADDRESS_START_MAIN_UNIT_UPDATING_TEXT0       63U
#define Y_ADDRESS_START_MAIN_UNIT_UPDATING_TEXT0       85U

#define X_ADDRESS_START_PICTURE_TOGGLE   72U
#define Y_ADDRESS_START_PICTURE_TOGGLE   34U
#define X_ADDRESS_END_PICTURE_TOGGLE     87U
#define Y_ADDRESS_END_PICTURE_TOGGLE     45U

void LCD_GUI_Init(void);
void LCD_GUI_Logo(void);
void LCD_GUI_MainUnitUpdating(void);
void LCD_GUI_pictureToggle(void);

uint8_t LCD_GUI_PutChar(uint8_t c, uint16_t  x, uint16_t  y, FONT_INFO *pFont, uint16_t fColor, uint16_t bColor);
void LCD_GUI_PutStr(const uint8_t *pString, uint16_t  x, uint16_t  y, FONT_INFO *pFont, uint16_t fColor, uint16_t bColor);
void LCD_GUI_put_text_roboto_12_Light (uint8_t x0, uint8_t y0, uint8_t textSize, uint8_t* symb_12_Light, uint16_t textColor);
void LCD_GUI_put_text_roboto_26_medium(uint8_t symb_26_medium);

void LCD_GUI_SleepIn(void);
void LCD_GUI_SleepOut(void);

#endif
